/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.3.1/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    implementation(libs.lucene.core)
    implementation(libs.lucene.queries)
    implementation(libs.lucene.queryparser)
    implementation(libs.lucene.highlighter)
    implementation(libs.lucene.analysis.common)

    implementation(libs.exposed.core)
    implementation(libs.exposed.jdbc)
    implementation(libs.sqlite.jdbc)

    implementation(libs.clikt)
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use Kotlin Test test framework
            useKotlinTest("2.2.21")
        }
    }
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    applicationDefaultJvmArgs = listOf("-Xmx256m")

    // Define the main class for the application.
    mainClass = "dev.emailsfts.AppKt"
}

// // clikt was pulling in 2.3.0 which is incompatible with fwcd's Kotlin vscode extension
// have switched to the official JetBrains extension now
// configurations.all {
//     resolutionStrategy {
//         force("org.jetbrains.kotlin:kotlin-stdlib:2.2.21")
//     }
// }

// Allow standard input from `gradle run`
tasks.named<JavaExec>("run") {
    standardInput = System.`in`
}